### ISSUE TITLE
undefined method 'serviceLevelDescription'

### ISSUE THREAD

**Issue by walkeran** [walkeran/nagios-check_dellwarranty#1]
When running check_dellwarranty.rb with certain ServiceTags, it will bail out with the following error:

```
./check_dellwarranty.rb:225:in `get_dell_warranty': undefined method `serviceLevelDescription' for #<SOAP::Mapping::Object:0x3687970> (NoMethodError)
        from ./check_dellwarranty.rb:222:in `each'
        from ./check_dellwarranty.rb:222:in `get_dell_warranty'
        from ./check_dellwarranty.rb:264
```

This is because of Dell returning a less-than-ideal result, like the following:

``` xml
    <Entitlements>
      <EntitlementData>
        <Provider/>
        <StartDate>2011-03-14T00:00:00</StartDate>
        <EndDate>2016-03-15T00:00:00</EndDate>
        <DaysLeft>1294</DaysLeft>
        <EntitlementType>Active</EntitlementType>
      </EntitlementData>
      <EntitlementData>
        <Provider/>
        <StartDate>2011-03-14T00:00:00</StartDate>
        <EndDate>2014-03-15T00:00:00</EndDate>
        <DaysLeft>563</DaysLeft>
        <EntitlementType>Active</EntitlementType>
      </EntitlementData>
    </Entitlements>
```

A typical (AFAICT) response would contain EntitlementData similar to the following:

``` xml
    <EntitlementData>
      <ServiceLevelCode>GD</ServiceLevelCode>
      <ServiceLevelDescription>P, Gold or ProMCritical</ServiceLevelDescription>
      <Provider>DELL</Provider>
      <StartDate>2010-01-27T00:00:00</StartDate>
      <EndDate>2014-01-27T00:00:00</EndDate>
      <DaysLeft>516</DaysLeft>
      <EntitlementType>Active</EntitlementType>
    </EntitlementData>
```

The lack of Provider is acceptable, however the missing ServiceLevelCode/ServiceLevelDescription throws a wrench into things, as they are currently used to separate the different service types, to determine when a certain type of contract is going to expire.

**Comment by walkeran** [comment]
I think the best plan of attack is going to be to take the following route to determine expirations while looping through the entitlements:
- If the entitlement is expired, throw it out. I'm under the impression that people are more concerned about impending doom than one may have happened in the past. If I am wrong on this one, I can revisit the logic, but until I know how people would like this to be handled, it's much easier to just focus on the active licenses that are about to expire
- If the entitlement doesn't have a service level code, track it completely separate from every other service level
- If the entitlement has a service level code, continue like previously, lumping all the "alike" entitlements, and calculating the actual expiration date for that service level based on the endDate that is furthest in the future
