### ISSUE TITLE
Problem with the check, or Dells site

### ISSUE THREAD

**Issue by HakanQD** [walkeran/nagios-check_dellwarranty#3]
Hi,

I'm using Your check to check the warranty on our Dell servers.

I was using the older version, 0.5, until today and it displays an error.
I then found out that version 1.0 was available, since more than two years :-)
But when I use that i get this error:

/usr/lib/ruby/gems/1.8/gems/json-1.7.7/lib/json/common.rb:155:in `parse': 757: unexpected token at '<Fault xmlns:env="http://schemas.xmlsoap.org/soap/envelope/" xmlns="http://api.dell.com/faults"> (JSON::ParserError)
<Code xmlns="">eAPI-40102</Code>
<Url xmlns="">http://developer.dell.com/faults#eAPI-40102</Url>
<Message xmlns="">Failed to Authenticate User</Message>
<Reason xmlns="">User Identification failed in Key Management Service</Reason>
<Source xmlns="">Gateway</Source></Fault>'
    from /usr/lib/ruby/gems/1.8/gems/json-1.7.7/lib/json/common.rb:155:in`parse'
    from ./check_dellwarranty.rb:290:in `get_dell_warranty'
    from ./check_dellwarranty.rb:364
    from /usr/lib/ruby/1.8/timeout.rb:67:in`timeout'
    from ./check_dellwarranty.rb:363

The command looks like this:
./check_dellwarranty.rb -s 2Z5F5Y1 -w 45 -c 30 -l

Is the error coming from Dells site?

**Comment by walkeran** [comment]
Uhoh. All good things must come to an end, and it looks like Dell has finally deprecated some old APIs and locked down some credentials. I'll admit that this script was using API credentials that were found on the internet, being used by people for the same purpose. It looks like that API key is now turned off, and API access now costs money: https://developer.dell.com/service-ent

We quit using the check_dellwarranty script in-house, because Dell's API was so terrible for the last couple of years, but I'll revisit this in my free time to see if I can figure out what it takes to get API access, if it costs anything, if this script would have to be rewritten, etc.

Thanks for reporting this!

**Comment by HakanQD** [comment]
Hi

I've found another check that still works though and we will use that, but yours was much nicer :)

HÅKAN BJÖRK
Systemkonsult
hakan.bjork@qd.semailto:hakan.bjork@qd.se|

SERVICEDESK:
support@qd.semailto:support@qd.se | 010-218 00 01tel:010-218%2000%2001
synpunkter@qd.semailto:synpunkter@qd.se  | www.qd.se/shophttp://www.qd.se/shop

www.QD.sehttp://www.QD.se Based in Sweden

28 apr. 2016 kl. 16:44 skrev Andy Walker <notifications@github.com<mailto:notifications@github.com>>:

Uhoh. All good things must come to an end, and it looks like Dell has finally deprecated some old APIs and locked down some credentials. I'll admit that this script was using API credentials that were found on the internet, being used by people for the same purpose. It looks like that API key is now turned off, and API access now costs money: https://developer.dell.com/service-ent

We quit using the check_dellwarranty script in-house, because Dell's API was so terrible for the last couple of years, but I'll revisit this in my free time to see if I can figure out what it takes to get API access, if it costs anything, if this script would have to be rewritten, etc.

Thanks for reporting this!
